Make a specification for buttonlog (part of work)
sahlet-official/buttonlog pull request #13
Opened 2022-09-19 14:30 UTC by sahlet-official

Partly resolve #9

2022-09-19 14:41 UTC, Yura-0 approved these changes

2022-09-19 14:41 UTC, naila135 approved these changes

2022-09-19 14:41 UTC, Yura-0 approved these changes

2022-09-19 14:44 UTC, Yura-0 approved these changes

2022-09-19 14:44 UTC, Yura-0 approved these changes

2022-09-19 14:46 UTC, Yura-0 commented on Specification/Specification.md
> +       - records: <number of records>
I think, this variant the best.

2022-09-19 14:47 UTC, Yura-0 approved these changes

2022-09-19 14:47 UTC, Yura-0 approved these changes

2022-09-19 14:48 UTC, Yura-0 approved these changes

2022-09-19 14:49 UTC, Yura-0 approved these changes

2022-09-19 14:50 UTC, Yura-0 approved these changes

2022-09-19 14:50 UTC, Yura-0 approved these changes

2022-09-19 14:58 UTC, Yura-0 requested changes
I believe that you can add a whole toolkit to the menu button - the clear button, information about the application. And on the screen, leave the log, the field for the filter and view the user's log.

2022-09-19 15:01 UTC, naila135 commented on Specification/Specification.md
> +       - recycle bin
Recycle bin is more convenient.

2022-09-19 15:02 UTC, Yura-0 commented on Specification/Specification.md
> +When a clear log scenario is called - it opens the confirmation clear log window.<br>
On mobile phones, instead of opening an additional window, you can call up a confirmation message like "Do you want to do this? YES button and NO button". This is easier than calling the whole window. I think you meant it.

2022-09-19 15:02 UTC, Yura-0 approved these changes

2022-09-19 15:03 UTC, Yura-0 approved these changes

2022-09-19 15:06 UTC, Yura-0 approved these changes

2022-09-19 15:09 UTC, Yura-0 reviewed
I like the idea of ​​having transparent text in the Filter field and a log when nothing is written there. I think it looks stylish, and I think it can be left.

2022-09-19 15:10 UTC, Yura-0 approved these changes

2022-09-19 15:10 UTC, Yura-0 approved these changes

2022-09-19 15:11 UTC, Yura-0 approved these changes

2022-09-19 15:12 UTC, Yura-0 approved these changes

2022-09-19 15:12 UTC, Yura-0 approved these changes

2022-09-19 15:13 UTC, Yura-0 approved these changes

2022-09-19 15:13 UTC, Yura-0 approved these changes

2022-09-19 15:14 UTC, Yura-0 approved these changes

2022-09-19 15:14 UTC, Yura-0 approved these changes

2022-09-19 15:15 UTC, Yura-0 approved these changes

2022-09-20 11:25 UTC, Yura-0 commented on Specification/Specification.md
> +       - records: &lt;number of records>
This is the best variant.

2022-09-20 11:28 UTC, Yura-0 commented on Specification/Specification.md
> +#### Menu screen
In principle, you can also use the menu, but there are quite a few buttons, so they can simply be placed on the main screen.

2022-09-20 11:31 UTC, Yura-0 commented on Specification/Specification.md
> +As a user, I want to have an option to clear the log through the confirmation window to be able to confirm or cancel the action.<br>
I think it's better not to create a full-sized window, but to display a message with YES and NO buttons. Perhaps you meant it.

2022-09-22 05:32 UTC, Sahlet approved these changes

2022-09-26 12:01 UTC, sahlet-official commented on Specification/Specification.md
> +       - records: &lt;number of records>
I agree

2022-09-26 12:02 UTC, sahlet-official commented on Specification/Specification.md
> +       - recycle bin
I agree

2022-09-26 12:19 UTC, sahlet-official commented on Specification/Specification.md
> +#### Menu screen
@naila135 
If we will talk about Buttonlog as a finished product with no more additional functions in the future - then I would agree with you.
But for me, as for Product Owner, it looks like this:
1. Buttonlog is like a template for future products.
If we build UI for Buttonlog scalable - it will cost much less to start a new product with Buttonlog as a base.
2. It is possible that with time it will be good to add some new functions to Buttonlog.
For example, if the functionality of Buttonlog will need a "Settings" screen, it is easy to add a new element to the menu list.
And so on with something else.

2022-09-26 12:20 UTC, sahlet-official commented on Specification/Specification.md
> +#### Menu screen
@Yura-0 
Look here please
https://github.com/sahlet-official/buttonlog/pull/13/files#r979954948

2022-09-26 13:28 UTC, Yura-0 submitted a review, later dismissed

2022-09-27 15:10 UTC, naila135 approved these changes

2022-09-27 15:10 UTC, naila135 commented on Specification/Specification.md
> +#### Menu screen
You are right

2022-09-27 15:38 UTC, merged