Designer view
sahlet-official/buttonlog pull request #18
Opened 2022-10-11 12:47 UTC by naila135

Resolve #10

2022-10-11 16:17 UTC, sahlet-official commented on Specification/Design/DesignerView/Iteration3.md
> +The final design will be divided into source files for developers.
Please change it to:

The [approved design]_(https://github.com/sahlet-official/buttonlog/tree/develop/Specification/Design/ApprovedDesign/ApprovedDesign.md) will be divided into source files for developers.

2022-10-11 16:17 UTC, sahlet-official commented on Specification/Design/FinalDesign/FinalDesign.md
> +This file represents final result of creating UX/UI for button log aplication.
Please
Change the file name to ApprovedDesign.md
Change the folder name to ApprovedDesign

2022-10-11 16:17 UTC, sahlet-official commented on Specification/Design/FinalDesign/FinalDesign.md
> +Color Palette: white, black.
Maybe
Color Palette: white, black, gray.
?

2022-10-11 16:17 UTC, sahlet-official commented on Specification/Design/FinalDesign/FinalDesign.md
> +Clear Log dialog:
Please change it to:

**Clear log confirmation window**:
Use
![image](https://user-images.githubusercontent.com/45210795/195145084-ded56f16-fb92-40e9-9850-bff8ce78061d.png)

to make bold text

2022-10-11 16:17 UTC, sahlet-official commented on Specification/Design/FinalDesign/FinalDesign.md
> +Main Screen:
Please change it to:

**Main screen**:
Use
![image](https://user-images.githubusercontent.com/45210795/195145084-ded56f16-fb92-40e9-9850-bff8ce78061d.png)


to make bold text

2022-10-11 16:17 UTC, sahlet-official commented on Specification/Design/FinalDesign/FinalDesign.md
> +About Screen:
Please change it to:

**About app screen**:
Use
![image](https://user-images.githubusercontent.com/45210795/195145084-ded56f16-fb92-40e9-9850-bff8ce78061d.png)

to make bold text

2022-10-16 12:23 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +Based on UX requirements and product owner requirements, the following specifications were developed for the UI interface:
done

2022-10-16 12:23 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +The UX scheme was based on the scheme from ProdOwnerView
ok, done

2022-10-16 12:24 UTC, naila135 commented on Specification/Design/FinalDesign/FinalDesign.md
> +This file represents final result of creating UX/UI for button log aplication.
done

2022-10-16 12:24 UTC, naila135 commented on Specification/Design/FinalDesign/FinalDesign.md
> +Color Palette: white, black.
You are right. Done

2022-10-16 12:24 UTC, naila135 commented on Specification/Design/FinalDesign/FinalDesign.md
> +Clear Log dialog:
Thanks for recomendations, done

2022-10-16 12:25 UTC, naila135 commented on Specification/Design/FinalDesign/FinalDesign.md
> +About Screen:
done

2022-10-16 12:25 UTC, naila135 commented on Specification/Design/FinalDesign/FinalDesign.md
> +Main Screen:
done

2022-10-17 12:39 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +ButtonLog UX/UI View by Designer
done

2022-10-17 12:39 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +Task: develop ux/ui for the button log application.
done

2022-10-17 13:46 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +The development of the UI interface was divided into iterations, each of which will be accompanied by consultations with the product owner and development team.
done

2022-10-17 13:46 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +The results of each iteration will be contributed to the repository, accompanied by a link to the Figma document.
done

2022-10-17 13:46 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +The results of each iteration will be contributed to the repository, accompanied by a link to the Figma document.
done

2022-10-17 13:46 UTC, naila135 commented on Specification/Design/DesignerView/Iteration1.md
> +Link for more details:
done

2022-10-17 13:49 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +- design should be user-oriented.
done

2022-10-17 13:50 UTC, naila135 commented on Specification/Design/DesignerView/Iteration1.md
> +-The color scheme has been changed and is now black and white and its shades
done

2022-10-17 13:50 UTC, naila135 commented on Specification/Design/DesignerView/Iteration1.md
> +-The color scheme has been changed and is now black and white and its shades
done

2022-10-17 13:50 UTC, naila135 commented on Specification/Design/DesignerView/Iteration3.md
> +This document is the result of the third(last) iteration of creating a UI interface for the ButtonLog application.
done

2022-10-17 13:50 UTC, naila135 commented on Specification/Design/DesignerView/Iteration3.md
> +The final design will be divided into source files for developers.
done

2022-10-18 10:29 UTC, Yura-0 submitted a review, later dismissed

2022-10-18 17:17 UTC, sahlet-official requested changes

2022-10-18 17:17 UTC, sahlet-official commented on Specification/Design/ApprovedDesign/ApprovedDesign.md
> +Color Palette: white, black, gray.
I think it is better to say
"shades of gray" instead "gray"

2022-10-18 17:17 UTC, sahlet-official commented on Specification/Design/FinalDesign/FinalDesign.md
> +Main Screen:
it hasn't been done yet
@naila135

note:
Do not make ":" bold.

Sorry for this minor correction.

2022-10-19 20:32 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +ButtonLog UX/UI View by Designer
ahhh now I understand what you mean, done

2022-10-19 20:32 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +Task: develop ux/ui for the button log application.
actually done

2022-10-19 20:33 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +The UX scheme was based on the scheme from ProdOwnerView
done

2022-10-19 20:37 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +The UX scheme was based on the scheme from ProdOwnerView
Can you tell me where it is not done, I looked through and could not find.

2022-10-19 20:40 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +- design should be user-oriented.
forgot about ApprovedDesign, now done.

2022-10-19 20:41 UTC, naila135 commented on Specification/Design/DesignerView/DesignerView.md
> +The results of each iteration will be contributed to the repository, accompanied by a link to the Figma document.
no problem, i fixed it

2022-10-19 20:43 UTC, naila135 commented on Specification/Design/FinalDesign/FinalDesign.md
> +Clear Log dialog:
done

2022-10-19 20:44 UTC, naila135 commented on Specification/Design/FinalDesign/FinalDesign.md
> +Main Screen:
done, nvm

2022-10-19 20:44 UTC, naila135 commented on Specification/Design/FinalDesign/FinalDesign.md
> +About Screen:
done

2022-10-19 20:44 UTC, naila135 commented on Specification/Design/ApprovedDesign/ApprovedDesign.md
> +This file represents final result of creating UX/UI for button log aplication.
done

2022-10-19 20:45 UTC, naila135 commented on Specification/Design/ApprovedDesign/ApprovedDesign.md
> +Color Palette: white, black, gray.
ok, done

2022-10-20 09:46 UTC, sahlet-official commented on Specification/Design/DesignerView/DesignerView.md
> +Task: develop ux/ui for the button log application.
it hasn't been at the moment of my previous review.
My comment was made at 7:17PM (GTM+2) 18.10.2022.
at this moment state of your branch related to the PR was this:
Follow the link and you will see, that changes have been done with commit at 10:31PM (GTM+2) 19.10.2022.
https://github.com/sahlet-official/buttonlog/pull/18/commits/d673382880931f3d8a15afd5ca6826535eda4a69

Please don't cheat on me.
You are lying in my face, I hate it.
Don't do that!!!!!!!!!!!!!

@naila135

2022-10-20 09:51 UTC, sahlet-official commented on Specification/Design/DesignerView/DesignerView.md
> +- design should be user-oriented.
it hasn't been done yet
@naila135

(in other lists also)
(in other documents also)

look at DesignerView/Readme.md
and all other documentation

2022-10-20 14:38 UTC, sahlet-official commented on Specification/Design/DesignerView/DesignerView.md
> +Task: develop ux/ui for the button log application.
it hasn't been done at the moment of my previous review.
My comment was made at 7:17PM (GTM+2) 18.10.2022.
at that moment state of your branch related to the PR was this:
Follow the link and you will see, that changes have been done with commit at 10:31PM (GTM+2) 19.10.2022.
https://github.com/sahlet-official/buttonlog/pull/18/commits/d673382880931f3d8a15afd5ca6826535eda4a69

Please don't cheat on me.
You are lying in my face, I don't like it.
Don't do that!!!!!!!!!!!!!

2022-10-20 15:32 UTC, sahlet-official commented on Specification/Design/DesignerView/Readme.md
> +After [clarification](./Specification/Design/DesignerView/Iteration1.md) of the task, the following changes were made to the customer's UX scheme:
it hasn't been done yet
@naila135

2022-10-26 09:16 UTC, sahlet-official requested changes

2022-11-14 14:45 UTC, sahlet-official approved these changes

2022-11-14 14:47 UTC, merged