Create buttonlog UI project
sahlet-official/buttonlog pull request #34
Opened 2022-11-05 11:43 UTC by Yura-0

2022-12-03 14:53 UTC, sahlet-official requested changes

2022-12-03 14:53 UTC, sahlet-official commented on Sources/buttonlog/flutter_buttonlog/.gitignore
> +/android/*
change folder path from
"buttonlog/flutter_buttonlog/"
to
"buttonlog_flutter_app/"

info may needed:
https://stackoverflow.com/questions/46694153/changing-the-project-name
https://www.youtube.com/watch?v=nVEKzWKbNZI&ab_channel=dbestech

2022-12-03 14:53 UTC, sahlet-official commented on Sources/buttonlog/flutter_buttonlog/README.md
> +# flutter_buttonlog
rename to buttonlog_flutter_app

2022-12-03 14:53 UTC, sahlet-official commented on Sources/buttonlog/flutter_buttonlog/README.md
> +# flutter_buttonlog
rename the file from "README.md" to "Readme.md"

note: your code in your fork is not updated, there 4 commits behind, update it please
![image](https://user-images.githubusercontent.com/45210795/205444994-dd015382-5c10-4bc3-9402-b29f525915b4.png)

2022-12-03 14:53 UTC, sahlet-official commented on Sources/buttonlog/flutter_buttonlog/README.md
> +UI component of the Buttonlog project.<br/>
Remove this line please, because it is possible that we will put service inside the flutter project.

Or change the line to:
How to setup the project

2022-12-03 14:53 UTC, sahlet-official commented on Sources/buttonlog/flutter_buttonlog/README.md
> +To run the project, follow these steps:<br/>
no-no-no-no

Look for "How to create readme for flutter project"
or
"How to create readme for GitHub opensource project"

Copy folders from the repository or edit files to be able to run project - no-no-no-no
maximum what another developer should to to setup project on new computer - is to run some commands or setup ENVIRONMENT

You should simplify and automate this process as much as possible
Look for examples or guides.
There are some that I found (maybe you need some extra):
https://github.com/zubairehman/flutter-boilerplate-project/blob/master/README.md
https://dev.to/github/how-to-create-the-perfect-readme-for-your-open-source-project-1k69
https://github.com/topics/flutter-project
https://github.com/topics/flutter-beginners

Look for examples of flutter opensource projects - it will help you.
Also, you may need to write some script to automate the project setup.
It maybe *.bat file or some more modern script.

2022-12-06 15:56 UTC, sahlet-official requested changes

2022-12-06 15:56 UTC, sahlet-official commented on Sources/buttonlog_flutter_app/README.md
> +of the above at this [link](https://docs.flutter.dev/get-started/install).
Well done

2022-12-10 17:02 UTC, sahlet-official requested changes

2022-12-10 17:02 UTC, sahlet-official commented on Sources/ui-mockup/buttonlog_flutter_app/lib/main_activity.dart
> +                      ]),
I think ")"
should be on the next line under the start of the word "child" in line №113

2022-12-13 10:47 UTC, Yura-0 commented on Sources/ui-mockup/buttonlog_flutter_app/lib/main_activity.dart
> +                  MediaQuery.of(context).size.width / 20,
Line 35 is responsible for dynamically changing the padding of the container and therefore its size depending on the physical screen size of the device. So I tried this technique and did not see a ban on such a calculation in the documentation.

2022-12-14 13:26 UTC, sahlet-official requested changes

2022-12-14 13:26 UTC, sahlet-official commented on Sources/ui-mockup/buttonlog_flutter_app/lib/main_activity.dart
> +                  MediaQuery.of(context).size.width / 20,
filteInputPadding

2022-12-14 13:26 UTC, sahlet-official commented on Sources/ui-mockup/buttonlog_flutter_app/lib/main_activity.dart
> +                onSubmitted: (String value) async {
I think it is redundant, remove it please.

2022-12-14 13:26 UTC, sahlet-official commented on Sources/ui-mockup/buttonlog_flutter_app/lib/main_activity.dart
> +              height: MediaQuery.of(context).size.height / 20,
same - make such count not inline (not in parameters passing), but in another place.
make it like with filteInputPadding

2022-12-14 13:26 UTC, sahlet-official commented on Sources/ui-mockup/buttonlog_flutter_app/lib/main_activity.dart
> +                      'assets/images/info_button.svg',
Create a separate Assets file that will contain the Assets class and it will list public constants with which the paths to the assets will be written, and transfer all the paths to the assets there, and then refer to the constants from this class in the right places.

2022-12-14 13:26 UTC, sahlet-official commented on Sources/ui-mockup/buttonlog_flutter_app/lib/about.dart
> +            height: MediaQuery.of(context).size.height / 20,
Use same approach as with filteInputPadding please

2022-12-14 13:26 UTC, sahlet-official commented on Sources/ui-mockup/buttonlog_flutter_app/lib/about.dart
> +                "Very interesting and important info about app, it's authors etc.",
Create a separate Texts file that will contain the Texts class and it will list public constants with all texts that is needed in the App, transfer all the texts to Texts class constants there, and then refer to the constants from this class in the right places.

2022-12-14 13:40 UTC, sahlet-official requested changes

2022-12-14 13:40 UTC, sahlet-official commented on Sources/ui-mockup/buttonlog_flutter_app/lib/main_activity.dart
> +import 'clear_answer.dart';
Fix all files imports according to dart best practice

2022-12-19 09:02 UTC, sahlet-official approved these changes
It is far to be ideal (if we say about code quality).
but it is already not bad, pretty good for Mockup!!!

2022-12-19 09:21 UTC, merged